version: '3.7'
services:
  web:        
    build: ./docker/apache
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
  db:
    build: ./docker/mysql            
    ports:
      - 3306:3306
